services:
  matching-service:
    image: homiehub-recommendation-api:latest
    container_name: matching-service
    ports:
      - "8080:8080"
    networks:
      - homiehub-network
    restart: unless-stopped

  agent-service:
    image: homiehub-llm-agent-service:latest
    container_name: agent-service
    ports:
      - "4000:8080"
    environment:
      - MATCHING_SERVICE_URL=http://matching-service:8080
    env_file:
      - .env
    networks:
      - homiehub-network
    depends_on:
      - matching-service
    restart: unless-stopped

networks:
  homiehub-network:
    driver: bridge
